---
################################################################
# Configurations for project 14
################################################################

- hosts: nginx
- name: nginx assignment
  import_playbook: ../static-assignments/nginx-proxy.yml

- name: import db files
  import_playbook: ../static-assignments/db.yml

# - hosts: todo
# - name: Deploy the todo application
#   import_playbook: ../static-assignments/deployment.yml

# - hosts: artifactory
# - name: artifactory assignment
#   import_playbook: ../static-assignments/artifactory.yml

# - hosts: sonar
# - name: sonar assignment
#   import_playbook: ../static-assignments/sonar.yml

################################################################
# Configurations for project 13
################################################################

# - name: importing common file
#   become: true
#   import_playbook: ../static-assignments/common.yml
#   tags:
#     - always

# - name: uat-webserver assignment
#   import_playbook: ../static-assignments/uat-webservers.yml

# - name: include env-vars file
#   import_playbook: ../dynamic-assignments/env-vars.yml
#   tags:
#      - always

# - name: import db files
#   import_playbook: ../static-assignments/db.yml

# - name: Loadbalancers assignment
#   import_playbook: ../static-assignments/loadbalancers.yml
#   when: load_balancer_is_required 
   